export const cities = [
  { name: "Andorra la Vella", country: "Andorra" },
  { name: "Dubai", country: "United Arab Emirates" },
  { name: "Kabul", country: "Afghanistan" },
  { name: "Saint John's", country: "Antigua and Barbuda" },
  { name: "The Valley", country: "Anguilla" },
  { name: "Tirana", country: "Albania" },
  { name: "Yerevan", country: "Armenia" },
  { name: "Luanda", country: "Angola" },
  { name: "Buenos Aires", country: "Argentina" },
  { name: "Pago Pago", country: "American Samoa" },
  { name: "Vienna", country: "Austria" },
  { name: "Sydney", country: "Australia" },
  { name: "Oranjestad", country: "Aruba" },
  { name: "Mariehamn", country: "Alland Islands" },
  { name: "Baku", country: "Azerbaijan" },
  { name: "Sarajevo", country: "Bosnia and Herzegovina" },
  { name: "Bridgetown", country: "Barbados" },
  { name: "Dhaka", country: "Bangladesh" },
  { name: "Brussels", country: "Belgium" },
  { name: "Ouagadougou", country: "Burkina Faso" },
  { name: "Sofia", country: "Bulgaria" },
  { name: "Manama", country: "Bahrain" },
  { name: "Bujumbura", country: "Burundi" },
  { name: "Porto-Novo", country: "Benin" },
  { name: "Gustavia", country: "Saint Barthelemy" },
  { name: "Hamilton", country: "Bermuda" },
  { name: "Bandar Seri Begawan", country: "Brunei Darussalam" },
  { name: "La Paz", country: "Bolivia" },
  { name: "Brasilia", country: "Brazil" },
  { name: "Nassau", country: "Bahamas" },
  { name: "Thimphu", country: "Bhutan" },
  { name: "Gaborone", country: "Botswana" },
  { name: "Minsk", country: "Belarus" },
  { name: "Belmopan", country: "Belize" },
  { name: "Ottawa", country: "Canada" },
  { name: "West Island", country: "Cocos (Keeling) Islands" },
  { name: "Kinshasa", country: "Congo, Democratic Republic of the" },
  { name: "Bangui", country: "Central African Republic" },
  { name: "Brazzaville", country: "Congo, Republic of the" },
  { name: "Bern", country: "Switzerland" },
  { name: "Abidjan", country: "Cote d'Ivoire" },
  { name: "Avarua", country: "Cook Islands" },
  { name: "Santiago", country: "Chile" },
  { name: "Yaounde", country: "Cameroon" },
  { name: "Beijing", country: "China" },
  { name: "Bogotá", country: "Colombia" },
  { name: "San Jose", country: "Costa Rica" },
  { name: "Havana", country: "Cuba" },
  { name: "Praia", country: "Cape Verde" },
  { name: "Willemstad", country: "Curacao" },
  { name: "Flying Fish Cove", country: "Christmas Island" },
  { name: "Nicosia", country: "Cyprus" },
  { name: "Prague", country: "Czech Republic" },
  { name: "Berlin", country: "Germany" },
  { name: "Djibouti", country: "Djibouti" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Roseau", country: "Dominica" },
  { name: "Santo Domingo", country: "Dominican Republic" },
  { name: "Algiers", country: "Algeria" },
  { name: "Quito", country: "Ecuador" },
  { name: "Tallinn", country: "Estonia" },
  { name: "Cairo", country: "Egypt" },
  { name: "Laayoune", country: "Western Sahara" },
  { name: "Asmara", country: "Eritrea" },
  { name: "Madrid", country: "Spain" },
  { name: "Addis Ababa", country: "Ethiopia" },
  { name: "Helsinki", country: "Finland" },
  { name: "Suva", country: "Fiji" },
  { name: "Stanley", country: "Falkland Islands (Malvinas)" },
  { name: "Palikir", country: "Micronesia, Federated States of" },
  { name: "Tórshavn", country: "Faroe Islands" },
  { name: "Paris", country: "France" },
  { name: "Libreville", country: "Gabon" },
  { name: "London", country: "United Kingdom" },
  { name: "St. George's", country: "Grenada" },
  { name: "Tbilisi", country: "Georgia" },
  { name: "Cayenne", country: "French Guiana" },
  { name: "St. Peter Port", country: "Guernsey" },
  { name: "Accra", country: "Ghana" },
  { name: "Gibraltar", country: "Gibraltar" },
  { name: "Nuuk", country: "Greenland" },
  { name: "Banjul", country: "Gambia" },
  { name: "Conakry", country: "Guinea" },
  { name: "Basse-Terre", country: "Guadeloupe" },
  { name: "Malabo", country: "Equatorial Guinea" },
  { name: "Athens", country: "Greece" },
  { name: "King Edward Point", country: "South Georgia and the South Sandwich Islands" },
  { name: "Guatemala City", country: "Guatemala" },
  { name: "Hagåtña", country: "Guam" },
  { name: "Bissau", country: "Guinea-Bissau" },
  { name: "Georgetown", country: "Guyana" },
  { name: "Hong Kong", country: "Hong Kong" },
  { name: "Tegucigalpa", country: "Honduras" },
  { name: "Zagreb", country: "Croatia" },
  { name: "Port-au-Prince", country: "Haiti" },
  { name: "Budapest", country: "Hungary" },
  { name: "Jakarta", country: "Indonesia" },
  { name: "Dublin", country: "Ireland" },
  { name: "Jerusalem", country: "Israel" },
  { name: "Douglas", country: "Isle of Man" },
  { name: "New Delhi", country: "India" },
  { name: "Diego Garcia", country: "British Indian Ocean Territory" },
  { name: "Baghdad", country: "Iraq" },
  { name: "Tehran", country: "Iran, Islamic Republic of" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "Rome", country: "Italy" },
  { name: "Saint Helier", country: "Jersey" },
  { name: "Kingston", country: "Jamaica" },
  { name: "Amman", country: "Jordan" },
  { name: "Tokyo", country: "Japan" },
  { name: "Nairobi", country: "Kenya" },
  { name: "Bishkek", country: "Kyrgyzstan" },
  { name: "Phnom Penh", country: "Cambodia" },
  { name: "Tarawa", country: "Kiribati" },
  { name: "Moroni", country: "Comoros" },
  { name: "Basseterre", country: "Saint Kitts and Nevis" },
  { name: "Pyongyang", country: "Korea, Democratic People's Republic of" },
  { name: "Seoul", country: "Korea, Republic of" },
  { name: "Kuwait City", country: "Kuwait" },
  { name: "George Town", country: "Cayman Islands" },
  { name: "Nur-Sultan", country: "Kazakhstan" },
  { name: "Vientiane", country: "Lao People's Democratic Republic" },
  { name: "Beirut", country: "Lebanon" },
  { name: "Castries", country: "Saint Lucia" },
  { name: "Vaduz", country: "Liechtenstein" },
  { name: "Colombo", country: "Sri Lanka" },
  { name: "Monrovia", country: "Liberia" },
  { name: "Maseru", country: "Lesotho" },
  { name: "Vilnius", country: "Lithuania" },
  { name: "Luxembourg City", country: "Luxembourg" },
  { name: "Riga", country: "Latvia" },
  { name: "Tripoli", country: "Libya" },
  { name: "Rabat", country: "Morocco" },
  { name: "Monaco", country: "Monaco" },
  { name: "Chisinau", country: "Moldova, Republic of" },
  { name: "Podgorica", country: "Montenegro" },
  { name: "Marigot", country: "Saint Martin (French part)" },
  { name: "Antananarivo", country: "Madagascar" },
  { name: "Majuro", country: "Marshall Islands" },
  { name: "Skopje", country: "Macedonia, the Former Yugoslav Republic of" },
  { name: "Bamako", country: "Mali" },
  { name: "Naypyidaw", country: "Myanmar" },
  { name: "Ulaanbaatar", country: "Mongolia" },
  { name: "Macau", country: "Macao" },
  { name: "Saipan", country: "Northern Mariana Islands" },
  { name: "Fort-de-France", country: "Martinique" },
  { name: "Nouakchott", country: "Mauritania" },
  { name: "Plymouth", country: "Montserrat" },
  { name: "Valletta", country: "Malta" },
  { name: "Port Louis", country: "Mauritius" },
  { name: "Male", country: "Maldives" },
  { name: "Lilongwe", country: "Malawi" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Maputo", country: "Mozambique" },
  { name: "Windhoek", country: "Namibia" },
  { name: "Noumea", country: "New Caledonia" },
  { name: "Niamey", country: "Niger" },
  { name: "Kingston", country: "Norfolk Island" },
  { name: "Abuja", country: "Nigeria" },
  { name: "Managua", country: "Nicaragua" },
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Oslo", country: "Norway" },
  { name: "Kathmandu", country: "Nepal" },
  { name: "Yaren", country: "Nauru" },
  { name: "Alofi", country: "Niue" },
  { name: "Wellington", country: "New Zealand" },
  { name: "Muscat", country: "Oman" },
  { name: "Panama City", country: "Panama" },
  { name: "Lima", country: "Peru" },
  { name: "Papeete", country: "French Polynesia" },
  { name: "Port Moresby", country: "Papua New Guinea" },
  { name: "Manila", country: "Philippines" },
  { name: "Islamabad", country: "Pakistan" },
  { name: "Warsaw", country: "Poland" },
  { name: "Saint-Pierre", country: "Saint Pierre and Miquelon" },
  { name: "Adamstown", country: "Pitcairn" },
  { name: "San Juan", country: "Puerto Rico" },
  { name: "Ramallah", country: "Palestine, State of" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Ngerulmud", country: "Palau" },
  { name: "Asuncion", country: "Paraguay" },
  { name: "Doha", country: "Qatar" },
  { name: "Saint-Denis", country: "Reunion" },
  { name: "Bucharest", country: "Romania" },
  { name: "Belgrade", country: "Serbia" },
  { name: "Moscow", country: "Russian Federation" },
  { name: "Kigali", country: "Rwanda" },
  { name: "Riyadh", country: "Saudi Arabia" },
  { name: "Honiara", country: "Solomon Islands" },
  { name: "Victoria", country: "Seychelles" },
  { name: "Khartoum", country: "Sudan" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Singapore", country: "Singapore" },
  { name: "Jamestown", country: "Saint Helena" },
  { name: "Ljubljana", country: "Slovenia" },
  { name: "Longyearbyen", country: "Svalbard and Jan Mayen" },
  { name: "Bratislava", country: "Slovakia" },
  { name: "Freetown", country: "Sierra Leone" },
  { name: "San Marino", country: "San Marino" },
  { name: "Dakar", country: "Senegal" },
  { name: "Mogadishu", country: "Somalia" },
  { name: "Paramaribo", country: "Suriname" },
  { name: "Juba", country: "South Sudan" },
  { name: "Sao Tome", country: "Sao Tome and Principe" },
  { name: "San Salvador", country: "El Salvador" },
  { name: "Philipsburg", country: "Sint Maarten (Dutch part)" },
  { name: "Damascus", country: "Syrian Arab Republic" },
  { name: "Mbabane", country: "Swaziland" },
  { name: "Cockburn Town", country: "Turks and Caicos Islands" },
  { name: "N'Djamena", country: "Chad" },
  { name: "Port-aux-Français", country: "French Southern Territories" },
  { name: "Lomé", country: "Togo" },
  { name: "Bangkok", country: "Thailand" },
  { name: "Dushanbe", country: "Tajikistan" },
  { name: "Fakaofo", country: "Tokelau" },
  { name: "Dili", country: "Timor-Leste" },
  { name: "Ashgabat", country: "Turkmenistan" },
  { name: "Tunis", country: "Tunisia" },
  { name: "Nukuʻalofa", country: "Tonga" },
  { name: "Ankara", country: "Turkey" },
  { name: "Port of Spain", country: "Trinidad and Tobago" },
  { name: "Funafuti", country: "Tuvalu" },
  { name: "Taipei", country: "Taiwan, Republic of China" },
  { name: "Dodoma", country: "United Republic of Tanzania" },
  { name: "Kyiv", country: "Ukraine" },
  { name: "Kampala", country: "Uganda" },
  { name: "Washington, D.C.", country: "United States" },
  { name: "Montevideo", country: "Uruguay" },
  { name: "Tashkent", country: "Uzbekistan" },
  { name: "Vatican City", country: "Holy See (Vatican City State)" },
  { name: "Kingstown", country: "Saint Vincent and the Grenadines" },
  { name: "Caracas", country: "Venezuela" },
  { name: "Road Town", country: "British Virgin Islands" },
  { name: "Charlotte Amalie", country: "US Virgin Islands" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Port Vila", country: "Vanuatu" },
  { name: "Mata-Utu", country: "Wallis and Futuna" },
  { name: "Apia", country: "Samoa" },
  { name: "Pristina", country: "Kosovo" },
  { name: "Sanaa", country: "Yemen" },
  { name: "Mamoudzou", country: "Mayotte" },
  { name: "Pretoria", country: "South Africa" },
  { name: "Lusaka", country: "Zambia" },
  { name: "Harare", country: "Zimbabwe" },
];
